### PR TITLE
add vuex stores

### PR DESCRIPTION
**Pull request by dman776**
add vuex stores and business logic

### CODE REVIEW

**Comment by ab7pa** [comment]
@dman776 when I run on PR#13 the Mesh Nodes expansion-headers display okay, but when I click on a row to see the expansion-panel it throws the error below.  I'm not sure why I'm seeing this on my machine -- maybe I'm missing a module that needs to be installed?

> TypeError: state.services is undefined
>     getServicesByIp services.js:21
>     render servicechips.vue:8
>     VueJS 21

This happens on the Local Hosts rows and the Current Neighbors rows.  Also, on the Current Neighbors rows I'm only seeing the new label but no _Est. Thru_ values are displayed.  I'm also seeing the Web Content process taking ~100% of the CPU.  Again, not sure why.

**Review by ab7pa — COMMENTED** [review]
On **Current Neighbors** every expansion panel shows "No services available" even though the **api** returns a complete list of services.  Not sure why.

**Comment by dman776** [comment]
I fixed it today

Thanks,
Darryl

**Comment by ab7pa** [comment]
I tested this today with all the new **api** code, and it works really well.  Huge progress!
One thing I noticed is on the _Current Neighbors_ display I still cannot see the services for nodes that I know have services.  Not sure why, even though all the services are included in the **api** data.

**Comment by ab7pa** [comment]
The reason I wasn't seeing services in the _Current Neighbors_ list is because my test node is mainly connected via tunnels.  None of the tunnel nodes show any of their services, even though they all have some.  This is because the **api** data for _mesh=services_ has each service bound to the **RF** IP address of each node.  An RF connected node may be the only type that can display its services in the _Current Neighbors_ list.
currentNeighServiceList

Same is true for the Local Hosts display.  Services are bound to the RF interface IP of the node.
localHostsServiceList

**Review by ab7pa — APPROVED** [review]
I tested this PR today running on top of NB368 + PR114 and it worked well.

**Comment by ab7pa** [comment]
Looks great.  Thanks @dman776

**Pull request merged**
